services:
  
  catalogdb:
    image: mongo:8.2

  catalog:
    image: ${DOCKER_REGISTRY-}catalog
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile

  basketdb:
    image: redis:8.6-alpine

  basket:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile

volumes:
  mongo_data:
  