services:

  catalogdb:
    container_name: catalogdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  catalog:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DatabaseSettings__ConnectionString=mongodb://catalogdb:27017
      - DatabaseSettings__DatabaseName=CatalogDb
    depends_on:
      - catalogdb
    ports:
      - "8000:8080"

  basketdb:
    container_name: basketdb
    restart: always
    ports:
      - "6379:6379"
  
  basket:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - CacheSettings__ConnectionString=basketdb:6379 
    depends_on:
      - basketdb
    ports:
      - "8001:8080"
